### ISSUE TITLE
Training Details about office-31, visda 2017 and imagenet-caltech

### ISSUE THREAD

**Issue by stefanxinhong** [thuml/Universal-Domain-Adaptation#3]
The paper and the released code miss some training details about the mentioned dataset. Could you provide the yaml files of office-31, visda 2017 and imagenet-caltech? 
In addition, the usage of dataset imagenet-caltech is quite different in paper SAN and PADA. Could you provide the label files of imagenet-caltech used in the paper?
Thanks!

**Comment by youkaichao** [comment]
The config for office and visda are released in the latest commit https://github.com/thuml/Universal-Domain-Adaptation/commit/4422564b6bb6c003c82cddfc8c6ccffe282396ca . I think you can generate the label file for imagenet-caltech yourself, just be careful about the label mapping (the same category has different label_id in Imagenet and Caltech). How to train with ImageNet-caltech is also somewhat tedious, requiring many modifications and not compatible with the current code. That's why the code for ImageNet-caltech is not released.
